### ISSUE TITLE
Method for password recovery, suggestion ?

### ISSUE THREAD

**Issue by waiyong1106** [TrumpTaxi/Trump-Bus-management-System#1]

**Comment by jianhui123** [comment]
maybe we can try ask security question to user ?

**Comment by waiyong1106** [comment]
Its sound like a good idea, but before we make the decision, how about we ask our others teammate for agreement or other opinion ?

**Comment by jianhui123** [comment]
ok waiyong 1006

**Comment by ChunHan1996** [comment]
I think security question is not so suitable, because people may easily forget their answer, me myself also face this problem before.

**Comment by jianhui123** [comment]
then maybe we can try ask some question that related to themself , for example IC last 4 nombor

**Comment by waiyong1106** [comment]
I agreed with chun han, even for myself I do keep consistently forgot my security password.
Herm, is not bad for asking the question related to themselves but not sure that is that possible third party that who knew his/her ic number?

**Comment by inotsucker** [comment]
how about compare with phone number?

**Comment by waiyong1106** [comment]
phone number ... How about others though on the phone number?

**Comment by jianhui123** [comment]
sms verification?

**Comment by waiyong1106** [comment]
I think he mentioned by comparing the phone number.

**Comment by inotsucker** [comment]
sms verification sounds like not bad also ? we can have 2 method password recovery? don't we?

**Comment by waiyong1106** [comment]
Because the time for preparing project is limited, so we may applied one method for both staff and members.

**Comment by jianhui123** [comment]
compare phone number just same as ic number , how if i know the user phone nombor, 
sms verification is too hard for us , we have no mobile background

**Comment by inotsucker** [comment]
oo , roger that .

**Comment by waiyong1106** [comment]
I think we go will the Phone number or IC number will do.

**Comment by waiyong1106** [comment]
let's make a selection between one of them will do. 
Phone or Identity Card

**Comment by inotsucker** [comment]
i will vote for identity card because identity card important than phone , so people will remember their identity card number more than your phone number.

**Comment by jianhui123** [comment]
phone

**Comment by ChunHan1996** [comment]
phone is easier i think

**Comment by waiyong1106** [comment]
With all the agreement and disagreement, I announced that phone is selected ! 
CASE CLOSED !
